name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run:  docker build -t rhflorest/react-native . --file Dockerfile --tag latest
    - uses: actions/checkout@v2
    - name: login
      run: docker login -u rhflorest -p 16163788205as
    - uses: actions/checkout@v2
    - name: subir imagen 
      run: docker push rhflorest/react-native
      